export const ActionTypes = {
  GLOBAL: {
    ERROR: 'GLOBAL_ERROR',
  },
  MODAL: {
    SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
    SHOW_CREATE_ACCOUNT_MODAL: 'SHOW_CREATE_ACCOUNT_MODAL',
    SHOW_RESET_PASSWORD_MODAL: 'SHOW_RESET_PASSWORD_MODAL',
  },
  AUTH: {
    LOADING: 'AUTH_LOADING',
    ERROR: 'AUTH_ERROR',
    SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    RESET_PASSWORD: 'RESET_PASSWORD',
  },
  GAME: {
    SET_SELECTED_WEEK: 'GAME_SET_SELECTED_WEEK',
  },
};
